# ============================================
# 4. POD EXAMPLES USING SECRETS
# ============================================

---
# Pod using Secrets as Environment Variables
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: app
    image: myapp:1.0
    env:
    # Individual secret values
    - name: DB_HOST
      value: "mysql.default.svc.cluster.local"
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: database
    # Load all secret keys
    envFrom:
    - secretRef:
        name: api-keys
      prefix: API_

---
# Pod using Secrets as Volumes
apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: app
    image: myapp:1.0
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-credentials
      defaultMode: 0400  # Read-only for owner
      items:
      - key: username
        path: db-username
      - key: password
        path: db-password

---
# Pod using Docker Registry Secret
apiVersion: v1
kind: Pod
metadata:
  name: private-registry-pod
spec:
  containers:
  - name: app
    image: myregistry.com/myapp:1.0
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: docker-registry-secret

---
# Pod using TLS Secret
apiVersion: v1
kind: Pod
metadata:
  name: tls-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    volumeMounts:
    - name: tls-certs
      mountPath: /etc/nginx/ssl
      readOnly: true
    ports:
    - containerPort: 443
  volumes:
  - name: tls-certs
    secret:
      secretName: tls-secret
